### model
model_name_or_path: /cpfs/user/lengxue/ModeScope/Meta-Llama-3.1-8B #LLM-Research/Meta-Llama-3.1-8B  #meta-llama/Llama-3.1-8B

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: ultrachat_200k
template: llama3
cutoff_len: 2048
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 24

### output
output_dir: /cpfs/user/lengxue/code/multimodel/save_models/LF/llama3.1-8b_full_sft_base
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 2.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
