name: config of answer generation for arena-hard-v0.1

bench_name: arena-hard-v0.1_all

temperature: 0.0
max_tokens: 4096
num_choices: 1

# a list of model to generate answers
model_list:
  - llama3.1-8b_full_sft_base_checkpoint-1000
