# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int
#     system_prompt: str optional (add system instruction when generating model answer)

gpt-3.5-turbo-0125:
    model_name: gpt-3.5-turbo-0125
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-0314:
    model_name: gpt-4-0314
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-1106-preview:
    model_name: gpt-4-1106-preview
    endpoints: null
    api_type: openai
    parallel: 8

agi-gpt4o-ptu-lengxue:
    model_name: agi-gpt4o-ptu-lengxue
    endpoints: null
    api_type: xhs
    parallel: 30

TEMPLATE:
    model_name: TEMPLATE
    endpoints:
        - api_base: http://0.0.0.0:8000/v1
          api_key: 0
    api_type: openai
    parallel: 2
